"use client";
import React, { useState, useEffect } from "react";
import BlurredPopupLayout from "@/layout/blurredPopupLayout";
import { useRouter } from "next/navigation";
import Button from "@/components/Button";
import Inputcontainer from "@/components/Inputcontainer";
import Input from "@/components/Input";
import ToggleButton from "@/components/togglebutton";
import { useForm } from "react-hook-form";
import { useSelector } from "react-redux";
import { storeType } from "@/types/store.index";
import { categoryService } from "@/services/category.service";
import { aiProviderService } from "@/services/aiProvider.service";
import {
  Edit3,
  Check,
  X,
  Palette,
  Sliders,
  Sparkles,
  Loader2,
} from "lucide-react";
import cn from "classnames";

function UpdateCategory() {
  const router = useRouter();
  const isDark = useSelector((store: storeType) => store.DarkMode.isDarkMode);
  const [categoryId, setCategoryId] = useState<string>("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [aiSuccessMessage, setAiSuccessMessage] = useState("");
  const [submitError, setSubmitError] = useState("");
  const [hasColors, setHasColors] = useState<boolean>(true);
  const [hasVariants, setHasVariants] = useState<boolean>(false);

  const {
    register,
    handleSubmit,
    setValue,
    getValues,
    formState: { errors },
  } = useForm({
    defaultValues: {
      name: "",
      description: "",
    },
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("categoryData");
      if (stored) {
        try {
          const parsed = JSON.parse(stored);
          setCategoryId(parsed._id || parsed.id || "");
          setValue("name", parsed.name || "");
          setValue("description", parsed.description || "");
          setHasColors(
            parsed.hasColors !== undefined ? Boolean(parsed.hasColors) : true,
          );
          setHasVariants(
            parsed.hasVariants !== undefined
              ? Boolean(parsed.hasVariants)
              : false,
          );
        } catch (e) {
          console.warn("Failed to parse categoryData from localStorage", e);
        }
      }
    }
  }, [setValue]);

  const handleGenerateDescription = async () => {
    const currentName = getValues("name");
    if (!currentName || currentName.trim().length === 0) {
      setSubmitError(
        "Please enter a Category Name first to generate description.",
      );
      return;
    }

    setIsGeneratingAI(true);
    setSubmitError("");
    setAiSuccessMessage("");

    try {
      const result =
        await aiProviderService.generateCategoryDetails(currentName);
      if (result.description) {
        setValue("description", result.description, { shouldValidate: true });
      }
      if (typeof result.hasColors === "boolean") {
        setHasColors(result.hasColors);
      }
      if (typeof result.hasVariants === "boolean") {
        setHasVariants(result.hasVariants);
      }
      setAiSuccessMessage("✨ Description & capabilities generated by AI!");
      setTimeout(() => setAiSuccessMessage(""), 4000);
    } catch (err) {
      console.warn("Failed to generate category description", err);
      setSubmitError("Failed to generate description. Please try again.");
    } finally {
      setIsGeneratingAI(false);
    }
  };

  const onSubmit = async (data: any) => {
    if (!categoryId) {
      setSubmitError("No category ID selected for update.");
      return;
    }

    setIsSubmitting(true);
    setSubmitError("");

    const payload = {
      name: data.name,
      description: data.description,
      hasColors,
      hasVariants,
    };

    const res = await categoryService.updateCategory(categoryId, payload);
    setIsSubmitting(false);

    if (res.ok) {
      if (typeof window !== "undefined") {
        localStorage.removeItem("categoryData");
      }
      router.back();
    } else {
      setSubmitError(
        res.message || "Failed to update category. Please try again.",
      );
    }
  };

  return (
    <BlurredPopupLayout
      title="Edit Category"
      subtitle="Modify category classification and variant capabilities"
      icon={<Edit3 size={20} />}
      isDark={isDark}
      maxWidth="max-w-lg"
      onClose={() => router.back()}
    >
      {submitError && (
        <div className="mb-4 p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs font-semibold flex items-center gap-2">
          <X size={14} className="shrink-0" />
          <span>{submitError}</span>
        </div>
      )}

      {aiSuccessMessage && (
        <div className="mb-4 p-3 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-semibold flex items-center gap-2 animate-in fade-in slide-in-from-top-1">
          <Sparkles size={14} className="shrink-0 text-cyan-400" />
          <span>{aiSuccessMessage}</span>
        </div>
      )}

      <form
        id="update-category-form"
        onSubmit={handleSubmit(onSubmit)}
        className="space-y-4"
      >
        <Inputcontainer
          label="Category Name"
          required
          error={errors?.name}
          isDark={isDark}
        >
          <Input
            id="name"
            placeholder="Enter category name"
            {...register("name", { required: "Category name is required" })}
          />
        </Inputcontainer>

        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <label
              htmlFor="description"
              className={cn(
                "text-xs font-semibold",
                isDark ? "text-slate-300" : "text-slate-700",
              )}
            >
              Description{" "}
              <span className="text-slate-400 font-normal">(Optional)</span>
            </label>
            <button
              type="button"
              onClick={handleGenerateDescription}
              disabled={isGeneratingAI}
              className={cn(
                "inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-semibold transition-all cursor-pointer shadow-sm disabled:opacity-50 disabled:cursor-not-allowed",
                isDark
                  ? "bg-gradient-to-r from-cyan-500/20 to-blue-500/20 hover:from-cyan-500/30 hover:to-blue-500/30 text-cyan-300 border border-cyan-500/30 hover:border-cyan-400/50"
                  : "bg-cyan-50 hover:bg-cyan-100 text-cyan-700 border border-cyan-200",
              )}
              title="Auto-generate description and recommended capabilities with AI"
            >
              {isGeneratingAI ? (
                <Loader2 size={12} className="animate-spin text-cyan-400" />
              ) : (
                <Sparkles size={12} className="text-cyan-400" />
              )}
              <span>
                {isGeneratingAI ? "Generating..." : "Generate Description"}
              </span>
            </button>
          </div>

          <textarea
            id="description"
            rows={3}
            placeholder="Brief description of this product classification..."
            {...register("description")}
            className={cn(
              "w-full px-4 py-2.5 rounded-xl text-sm transition-all resize-none border focus:outline-none focus:ring-1",
              isDark
                ? "bg-slate-950/60 border-slate-700/60 text-slate-100 placeholder-slate-500 focus:border-cyan-400 focus:ring-cyan-400/25"
                : "bg-white border-slate-200 text-slate-900 placeholder-slate-400 focus:border-cyan-500 focus:ring-cyan-500/25",
            )}
          />
        </div>

        {/* Variant & Color Capability Options */}
        <div
          className={cn(
            "p-4 rounded-2xl border space-y-3.5",
            isDark
              ? "bg-slate-950/40 border-slate-800"
              : "bg-slate-50 border-slate-200",
          )}
        >
          <p
            className={cn(
              "text-xs font-bold uppercase tracking-wider",
              isDark ? "text-cyan-400" : "text-cyan-700",
            )}
          >
            Inventory & Variant Capabilities
          </p>

          {/* Color Variants Toggle */}
          <div className="flex items-start justify-between gap-3">
            <div className="space-y-0.5">
              <div className="flex items-center gap-1.5">
                <Palette
                  size={15}
                  className={isDark ? "text-cyan-400" : "text-cyan-600"}
                />
                <span
                  className={cn(
                    "text-xs font-bold",
                    isDark ? "text-white" : "text-slate-900",
                  )}
                >
                  Enable Color Variants
                </span>
              </div>
              <p
                className={cn(
                  "text-[11px] leading-relaxed",
                  isDark ? "text-slate-400" : "text-slate-500",
                )}
              >
                Products in this category come in different colors with separate
                stock counts (e.g. Mobiles, Smartwatches). Turn off for Cables
                or Chargers.
              </p>
            </div>
            <div className="shrink-0 pt-0.5">
              <ToggleButton
                active={hasColors}
                handler={(val) => setHasColors(val)}
                activeLabel="Enabled"
                inactiveLabel="Disabled"
                isDark={isDark}
              />
            </div>
          </div>

          {/* Storage / Spec Variants Toggle */}
          <div className="flex items-start justify-between gap-3 pt-2 border-t border-slate-700/30">
            <div className="space-y-0.5">
              <div className="flex items-center gap-1.5">
                <Sliders
                  size={15}
                  className={isDark ? "text-blue-400" : "text-blue-600"}
                />
                <span
                  className={cn(
                    "text-xs font-bold",
                    isDark ? "text-white" : "text-slate-900",
                  )}
                >
                  Enable Storage / Spec Variants
                </span>
              </div>
              <p
                className={cn(
                  "text-[11px] leading-relaxed",
                  isDark ? "text-slate-400" : "text-slate-500",
                )}
              >
                Allows configuring RAM/Storage tiers (e.g. 8GB/128GB,
                12GB/256GB).
              </p>
            </div>
            <div className="shrink-0 pt-0.5">
              <ToggleButton
                active={hasVariants}
                handler={(val) => setHasVariants(val)}
                activeLabel="Enabled"
                inactiveLabel="Disabled"
                isDark={isDark}
              />
            </div>
          </div>
        </div>

        <div
          className={cn(
            "flex items-center justify-end gap-3 pt-4 border-t",
            isDark ? "border-slate-800/80" : "border-slate-100",
          )}
        >
          <Button
            type="button"
            name="Cancel"
            variant="ghost"
            isDark={isDark}
            handler={() => router.back()}
          />
          <Button
            type="submit"
            name="Save Changes"
            variant="primary"
            isDark={isDark}
            loading={isSubmitting}
            disabled={isSubmitting}
            icon={<Check size={16} />}
          />
        </div>
      </form>
    </BlurredPopupLayout>
  );
}

export default UpdateCategory;
